#!/bin/bash
# Full-finetune the dual-camera GE-Act planner from the strict step_030000
# initialization. Both main/wrist current and offset-8 future frames are encoded
# online by SigLIP2-large-patch16-256 and DA3-Large's last encoder layer.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLANNER_DIR="$(dirname "$HERE")"
REPO_ROOT="$(cd "$PLANNER_DIR/.." && pwd)"

WEIGHTS=${WEIGHTS:-/data/LFT-W02_data/junjie/weights}
GE_ACT_DATA_CONFIG=${GE_ACT_DATA_CONFIG:?set GE_ACT_DATA_CONFIG to a GE-Act YAML config}
INIT_PLANNER_CHECKPOINT=${INIT_PLANNER_CHECKPOINT:-/data/users/junjie/code/VLM4WAM_k1_zero2_bidir/outputs/qwen3vl2b_siglip2_da3_libero_cur_k1/step_030000}
SIGLIP2_MODEL_DIR=${SIGLIP2_MODEL_DIR:-$WEIGHTS/siglip2-large-patch16-256}
DA3_CKPT_DIR=${DA3_CKPT_DIR:-/data/LFT-W02_data/junjie/VLA_WM/WSA/checkpoints/DA3-LARGE-1.1}
OUTPUT_DIR=${OUTPUT_DIR:-$REPO_ROOT/outputs/qwen3vl_semantic_planner/ge_act_dual_camera_siglip2da3_fullft_30k}

MAX_STEPS=${MAX_STEPS:-30000}
FULL_FINETUNE=${FULL_FINETUNE:-1}
VIDEO_TARGET_TYPE=${VIDEO_TARGET_TYPE:-siglip2}
SIGLIP2_INPUT_SIZE=${SIGLIP2_INPUT_SIZE:-256}
SIGLIP2_GRID_SIZE=${SIGLIP2_GRID_SIZE:-16}
SEMANTIC_DIM=${SEMANTIC_DIM:-1024}
USE_DEPTH=${USE_DEPTH:-1}
DEPTH_TARGET_TYPE=${DEPTH_TARGET_TYPE:-da3}
DEPTH_DIM=${DEPTH_DIM:-2048}
DA3_PROCESS_RES=${DA3_PROCESS_RES:-224}
DA3_ALIGN_STRATEGY=${DA3_ALIGN_STRATEGY:-last_layer}
USE_CURRENT_ALIGNMENT=${USE_CURRENT_ALIGNMENT:-1}
INDEPENDENT_MODALITY_TASK_TOKENS=${INDEPENDENT_MODALITY_TASK_TOKENS:-1}
NUM_TASK_TOKENS=${NUM_TASK_TOKENS:-64}
NUM_KEYFRAMES=${NUM_KEYFRAMES:-1}
SEQUENCE_LENGTH=${SEQUENCE_LENGTH:-9}
KEYFRAME_SCHEME=${KEYFRAME_SCHEME:-even_future}
FUTURE_KEYFRAME_OFFSET=${FUTURE_KEYFRAME_OFFSET:-8}

if [[ "$FUTURE_KEYFRAME_OFFSET" != "8" ]]; then
  echo "[launch] GE-Act dual-camera planner requires FUTURE_KEYFRAME_OFFSET=8" >&2
  exit 2
fi

export GE_ACT_DATA_CONFIG INIT_PLANNER_CHECKPOINT SIGLIP2_MODEL_DIR DA3_CKPT_DIR
export OUTPUT_DIR MAX_STEPS FULL_FINETUNE VIDEO_TARGET_TYPE
export SIGLIP2_INPUT_SIZE SIGLIP2_GRID_SIZE SEMANTIC_DIM
export USE_DEPTH DEPTH_TARGET_TYPE DEPTH_DIM DA3_PROCESS_RES DA3_ALIGN_STRATEGY
export USE_CURRENT_ALIGNMENT INDEPENDENT_MODALITY_TASK_TOKENS NUM_TASK_TOKENS
export NUM_KEYFRAMES SEQUENCE_LENGTH KEYFRAME_SCHEME FUTURE_KEYFRAME_OFFSET
export HEAD_WARMSTART_CKPT=

exec bash "$PLANNER_DIR/lingbot_dino_4b/train_lingbot_dino_4b.sh"
