#!/bin/bash
# Fresh dual-camera K4 Qwen3-VL-2B planner training on OLA (8xH100).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLANNER_DIR="$(dirname "$HERE")"
REPO_ROOT="$(cd "$PLANNER_DIR/.." && pwd)"
cd "$REPO_ROOT"
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"

RUN_KIND=${RUN_KIND:-formal}
PY=${PY:-/data/users/junjie/envs/vlm4wam/bin/python}
MODEL_PATH=${MODEL_PATH:-/data/users/junjie/vlm4wam_2b/weights/Qwen3-VL-2B-Instruct}
SIGLIP2_MODEL_DIR=${SIGLIP2_MODEL_DIR:-/data/users/junjie/vlm4wam_2b/weights/siglip2-large-patch16-256}
DA3_CKPT_DIR=${DA3_CKPT_DIR:-/data/users/junjie/vlm4wam_2b/weights/DA3-LARGE-1.1}
DA3_CODE_ROOT=${DA3_CODE_ROOT:-/data/users/junjie/vlm4wam_2b/code/Depth-Anything-3}
GE_ACT_DATA_CONFIG=${GE_ACT_DATA_CONFIG:-$REPO_ROOT/ge_act/configs/ltx_model/libero/planner_data_libero_fastwam_ola.yaml}
OUTPUT_DIR=${OUTPUT_DIR:-$REPO_ROOT/outputs/qwen3vl2b_siglip2_da3_libero_dual_camera_k4_wsa}

# Fresh initialization is part of the experiment contract. Empty means empty;
# the delegated launcher must not substitute a legacy checkpoint or head source.
INIT_PLANNER_CHECKPOINT=
HEAD_WARMSTART_CKPT=

NUM_GPUS=${NUM_GPUS:-8}
USE_DEEPSPEED=${USE_DEEPSPEED:-1}
NUM_KEYFRAMES=${NUM_KEYFRAMES:-4}
SEQUENCE_LENGTH=${SEQUENCE_LENGTH:-9}
KEYFRAME_SCHEME=${KEYFRAME_SCHEME:-even_future}
USE_CURRENT_ALIGNMENT=${USE_CURRENT_ALIGNMENT:-0}
INDEPENDENT_MODALITY_TASK_TOKENS=${INDEPENDENT_MODALITY_TASK_TOKENS:-0}
SHARED_LATENT_PER_KEYFRAME=${SHARED_LATENT_PER_KEYFRAME:-32}
PRIVATE_LATENT_PER_KEYFRAME=${PRIVATE_LATENT_PER_KEYFRAME:-32}

BATCH_SIZE=${BATCH_SIZE:-8}
GRAD_ACCUM=${GRAD_ACCUM:-2}
EXPECTED_GLOBAL_BATCH=${EXPECTED_GLOBAL_BATCH:-128}
LR=${LR:-3e-5}
HEAD_LR=${HEAD_LR:-3e-4}
WARMUP_STEPS=${WARMUP_STEPS:-2500}
WEIGHT_DECAY=${WEIGHT_DECAY:-0.01}
MAX_STEPS=${MAX_STEPS:-30000}
SAVE_STEPS=${SAVE_STEPS:-5000}
SAVE_START_STEP=${SAVE_START_STEP:-20000}
NUM_WORKERS=${NUM_WORKERS:-8}
FULL_FINETUNE=${FULL_FINETUNE:-1}

VIDEO_TARGET_TYPE=${VIDEO_TARGET_TYPE:-siglip2}
SIGLIP2_INPUT_SIZE=${SIGLIP2_INPUT_SIZE:-256}
SIGLIP2_GRID_SIZE=${SIGLIP2_GRID_SIZE:-16}
SEMANTIC_DIM=${SEMANTIC_DIM:-1024}
USE_DEPTH=${USE_DEPTH:-1}
DEPTH_TARGET_TYPE=${DEPTH_TARGET_TYPE:-da3}
DEPTH_DIM=${DEPTH_DIM:-2048}
DEPTH_GRID_SIZE=${DEPTH_GRID_SIZE:-16}
DEPTH_LOSS_WEIGHT=${DEPTH_LOSS_WEIGHT:-0.004}
DA3_PROCESS_RES=${DA3_PROCESS_RES:-224}
DA3_ALIGN_STRATEGY=${DA3_ALIGN_STRATEGY:-wsa_multilayer}
DA3_TEACHER_LAYERS=${DA3_TEACHER_LAYERS:-11,15,19,23}
DA3_LAYER_WEIGHTS=${DA3_LAYER_WEIGHTS:-1.0,1.2,1.4,1.6}

if [[ "$RUN_KIND" == "smoke" ]]; then
  NUM_GPUS=1
  USE_DEEPSPEED=0
  BATCH_SIZE=1
  GRAD_ACCUM=1
  EXPECTED_GLOBAL_BATCH=1
  MAX_STEPS=1
  SAVE_STEPS=1
  SAVE_START_STEP=1
  NUM_WORKERS=1
  OUTPUT_DIR=${SMOKE_OUTPUT_DIR:-$REPO_ROOT/outputs/qwen3vl2b_dual_camera_k4_smoke}
elif [[ "$RUN_KIND" != "formal" ]]; then
  echo "[launch] RUN_KIND must be smoke or formal, got '$RUN_KIND'" >&2
  exit 2
fi

if [[ "$NUM_KEYFRAMES" != "4" || "$SEQUENCE_LENGTH" != "9" ]]; then
  echo "[launch] dual-camera contract requires K=4 and sequence_length=9" >&2
  exit 2
fi
if [[ "$USE_CURRENT_ALIGNMENT" != "0" ]]; then
  echo "[launch] K4 planner is future-only; USE_CURRENT_ALIGNMENT must be 0" >&2
  exit 2
fi

"$PY" "$HERE/preflight_dual_camera_k4.py" \
  --config "$GE_ACT_DATA_CONFIG" \
  --model-path "$MODEL_PATH" \
  --siglip2-model-dir "$SIGLIP2_MODEL_DIR" \
  --da3-ckpt-dir "$DA3_CKPT_DIR" \
  --da3-code-root "$DA3_CODE_ROOT" \
  --output-dir "$OUTPUT_DIR"

export PY MODEL_PATH SIGLIP2_MODEL_DIR DA3_CKPT_DIR DA3_CODE_ROOT
export GE_ACT_DATA_CONFIG OUTPUT_DIR INIT_PLANNER_CHECKPOINT HEAD_WARMSTART_CKPT
export NUM_GPUS USE_DEEPSPEED NUM_KEYFRAMES SEQUENCE_LENGTH KEYFRAME_SCHEME
export USE_CURRENT_ALIGNMENT INDEPENDENT_MODALITY_TASK_TOKENS
export SHARED_LATENT_PER_KEYFRAME PRIVATE_LATENT_PER_KEYFRAME
export BATCH_SIZE GRAD_ACCUM EXPECTED_GLOBAL_BATCH LR HEAD_LR WARMUP_STEPS
export WEIGHT_DECAY MAX_STEPS SAVE_STEPS SAVE_START_STEP NUM_WORKERS FULL_FINETUNE
export VIDEO_TARGET_TYPE SIGLIP2_INPUT_SIZE SIGLIP2_GRID_SIZE SEMANTIC_DIM
export USE_DEPTH DEPTH_TARGET_TYPE DEPTH_DIM DEPTH_GRID_SIZE DEPTH_LOSS_WEIGHT
export DA3_PROCESS_RES DA3_ALIGN_STRATEGY DA3_TEACHER_LAYERS DA3_LAYER_WEIGHTS

exec bash "$PLANNER_DIR/lingbot_dino_4b/train_lingbot_dino_4b.sh"
